
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ubuntu-k8s-etcd"
  config.vm.network "private_network", ip: "192.168.50.6"

  config.vm.provision "shell", path: "install_scripts/prepareHost.sh"
  config.vm.provision "shell", path: "install_scripts/installDocker.sh"
  config.vm.provider "virtualbox" do |vm|
    vm.name = "ubuntu-k8s-etcd"
    vm.gui = false
    vm.memory = 2048
    vm.cpus = 2
  end
end
