--- 
- name: Add user
  user:
    name: k8s
    shell: /bin/bash
    groups: sudo
    append: yes

- name: Configure k8s user to be able to use sudo without password
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^k8s\s'
    line: 'k8s ALL=(ALL:ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'

- name: Ensure ~/.ssh exists
  file:
    path: /home/k8s/.ssh
    state: directory
    mode: 0700
    group: k8s
    owner: k8s

- name: Ensure that ~/.ssh/authorised_keys exists
  copy:
    src: k8s_rsa.pub
    dest: /home/k8s/.ssh/authorized_keys
    mode: 0600
    group: k8s
    owner: k8s

- name: Ensure that ~/.ssh/k8s_rsa.pub exists
  copy:
    src: k8s_rsa.pub
    dest: /home/k8s/.ssh/k8s_rsa.pub
    mode: 0600
    group: k8s
    owner: k8s

- name: Ensure that ~/.ssh/k8s_rsa exists
  copy:
    src: k8s_rsa
    dest: /home/k8s/.ssh/k8s_rsa
    mode: 0600
    group: k8s
    owner: k8s
  
- name: set k8s user password
  shell: "echo 'k8s:k8s' | sudo chpasswd"





    