#apiVersion: apps/v1beta1
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins-vuk
spec:
  ports:
  - port: 8080
    protocol: TCP
  # type: LoadBalancer
  type: NodePort
  selector:
    app: jenkins-vuk