
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ubuntu-k8s-nfs"
  config.vm.network "private_network", ip: "192.168.50.103"
  config.vm.provision "file", source: "../keys/my_rsa.pub", destination: "/home/vagrant/.ssh/my_rsa.pub"
  config.vm.provision "shell", path: "../install_scripts/authorise_key.sh"

  config.vm.provider "virtualbox" do |vm|
    vm.name = "ubuntu-k8s-nfs"
    vm.gui = false
    vm.memory = 1024
    vm.cpus = 2
  end
end
