#apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin-vuk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-vuk
  template:
    metadata:
      labels:
        app: phpmyadmin-vuk
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: admin
        - name: PMA_HOST
          value: $MYSQL_SERVICE_HOST
        - name: PMA_PORT
          value: mysql