#apiVersion: apps/v1beta1
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin-vuk
spec:
  ports:
  - port: 8080
    protocol: TCP
  type: NodePort
  selector:
    app: phpmyadmin-vuk