#apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql-vuk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-vuk
  template:
    metadata:
      labels:
        app: mysql-vuk
    spec:
      containers:
      - name: mysql
        image: 192.168.56.7:5000/dmi-mysql:0.0.1
        ports:
        - containerPort: 3306