---
- name: Activate memory_hierarchy
  command: "echo 1 > /sys/fs/cgroup/memory.use_hierarchy"

- name: add docker repository key
  shell: "curl https://releases.rancher.com/install-docker/17.03.sh | sh"


- name: Add k8s user to docker group
  user:
    name: k8s
    groups: docker
    append: yes
- name: copy docker systemd port activation
  copy:
    src: docker-tcp.socket
    dest: /etc/systemd/system/docker-tcp.socket
    owner: root
    mode: 0600
- name: copy daemon.json config
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    mode: 0600

- name: Enable Docker tcp Socker
  command: systemctl enable docker-tcp.socket

# - name: Enable Docker socket
#   command: systemctl enable docker.socket

- name: stop docker socket
  command: sudo service docker stop

- name: start docker tcp socket
  command: systemctl start docker-tcp.socket

- name: start docker unix socket
  command: systemctl start docker.socket

- name: start docker daemon
  service: name=docker state=started